// This file is auto-generated by @hey-api/openapi-ts

import { type Options, getColorsPalette, getDevLogin, getSeadocs, postSeadocs, deleteSeadocsById, getSeadocsById, patchSeadocsById, getSeadocsByIdContent, putSeadocsByIdContent, getSeadocsIndex, deleteUploadsById, getUploadsById, getUploads, postUploads, getUsersMe, patchUsersMe } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { GetColorsPaletteData, GetDevLoginData, GetSeadocsData, PostSeadocsData, PostSeadocsResponse, DeleteSeadocsByIdData, GetSeadocsByIdData, PatchSeadocsByIdData, PatchSeadocsByIdResponse, GetSeadocsByIdContentData, PutSeadocsByIdContentData, GetSeadocsIndexData, DeleteUploadsByIdData, GetUploadsByIdData, GetUploadsData, PostUploadsData, PostUploadsResponse, GetUsersMeData, PatchUsersMeData, PatchUsersMeResponse } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getColorsPaletteQueryKey = (options?: Options<GetColorsPaletteData>) => createQueryKey('getColorsPalette', options);

/**
 * Получение цветов пользователей по умолчанию
 */
export const getColorsPaletteOptions = (options?: Options<GetColorsPaletteData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getColorsPalette({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getColorsPaletteQueryKey(options)
    });
};

export const getDevLoginQueryKey = (options?: Options<GetDevLoginData>) => createQueryKey('getDevLogin', options);

export const getDevLoginOptions = (options?: Options<GetDevLoginData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getDevLogin({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getDevLoginQueryKey(options)
    });
};

export const getSeadocsQueryKey = (options?: Options<GetSeadocsData>) => createQueryKey('getSeadocs', options);

export const getSeadocsOptions = (options?: Options<GetSeadocsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSeadocs({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSeadocsQueryKey(options)
    });
};

export const postSeadocsQueryKey = (options?: Options<PostSeadocsData>) => createQueryKey('postSeadocs', options);

export const postSeadocsOptions = (options?: Options<PostSeadocsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postSeadocs({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postSeadocsQueryKey(options)
    });
};

export const postSeadocsMutation = (options?: Partial<Options<PostSeadocsData>>): UseMutationOptions<PostSeadocsResponse, DefaultError, Options<PostSeadocsData>> => {
    const mutationOptions: UseMutationOptions<PostSeadocsResponse, DefaultError, Options<PostSeadocsData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postSeadocs({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteSeadocsByIdMutation = (options?: Partial<Options<DeleteSeadocsByIdData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteSeadocsByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteSeadocsByIdData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await deleteSeadocsById({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSeadocsByIdQueryKey = (options: Options<GetSeadocsByIdData>) => createQueryKey('getSeadocsById', options);

export const getSeadocsByIdOptions = (options: Options<GetSeadocsByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSeadocsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSeadocsByIdQueryKey(options)
    });
};

export const patchSeadocsByIdMutation = (options?: Partial<Options<PatchSeadocsByIdData>>): UseMutationOptions<PatchSeadocsByIdResponse, DefaultError, Options<PatchSeadocsByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchSeadocsByIdResponse, DefaultError, Options<PatchSeadocsByIdData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await patchSeadocsById({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSeadocsByIdContentQueryKey = (options: Options<GetSeadocsByIdContentData>) => createQueryKey('getSeadocsByIdContent', options);

export const getSeadocsByIdContentOptions = (options: Options<GetSeadocsByIdContentData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSeadocsByIdContent({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSeadocsByIdContentQueryKey(options)
    });
};

export const putSeadocsByIdContentMutation = (options?: Partial<Options<PutSeadocsByIdContentData>>): UseMutationOptions<unknown, DefaultError, Options<PutSeadocsByIdContentData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutSeadocsByIdContentData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await putSeadocsByIdContent({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSeadocsIndexQueryKey = (options?: Options<GetSeadocsIndexData>) => createQueryKey('getSeadocsIndex', options);

export const getSeadocsIndexOptions = (options?: Options<GetSeadocsIndexData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSeadocsIndex({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSeadocsIndexQueryKey(options)
    });
};

export const deleteUploadsByIdMutation = (options?: Partial<Options<DeleteUploadsByIdData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteUploadsByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteUploadsByIdData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await deleteUploadsById({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUploadsByIdQueryKey = (options: Options<GetUploadsByIdData>) => createQueryKey('getUploadsById', options);

export const getUploadsByIdOptions = (options: Options<GetUploadsByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUploadsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUploadsByIdQueryKey(options)
    });
};

export const getUploadsQueryKey = (options?: Options<GetUploadsData>) => createQueryKey('getUploads', options);

export const getUploadsOptions = (options?: Options<GetUploadsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUploads({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUploadsQueryKey(options)
    });
};

export const postUploadsQueryKey = (options: Options<PostUploadsData>) => createQueryKey('postUploads', options);

export const postUploadsOptions = (options: Options<PostUploadsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postUploads({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postUploadsQueryKey(options)
    });
};

export const postUploadsMutation = (options?: Partial<Options<PostUploadsData>>): UseMutationOptions<PostUploadsResponse, DefaultError, Options<PostUploadsData>> => {
    const mutationOptions: UseMutationOptions<PostUploadsResponse, DefaultError, Options<PostUploadsData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postUploads({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUsersMeQueryKey = (options?: Options<GetUsersMeData>) => createQueryKey('getUsersMe', options);

/**
 * Получение данных специфичных для Seadox Api
 */
export const getUsersMeOptions = (options?: Options<GetUsersMeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUsersMe({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUsersMeQueryKey(options)
    });
};

/**
 * Изменение профиля в Seadox
 */
export const patchUsersMeMutation = (options?: Partial<Options<PatchUsersMeData>>): UseMutationOptions<PatchUsersMeResponse, DefaultError, Options<PatchUsersMeData>> => {
    const mutationOptions: UseMutationOptions<PatchUsersMeResponse, DefaultError, Options<PatchUsersMeData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await patchUsersMe({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};