// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetDevLoginData, GetDevLoginResponses, GetSeadocsByIdData, GetSeadocsByIdResponses, GetSeadocsByIdErrors, GetSeadocsData, GetSeadocsResponses, GetUsersMeData, GetUsersMeResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getDevLogin = <ThrowOnError extends boolean = false>(options?: Options<GetDevLoginData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDevLoginResponses, unknown, ThrowOnError>({
        url: '/dev/login',
        ...options
    });
};

export const getSeadocsById = <ThrowOnError extends boolean = false>(options: Options<GetSeadocsByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetSeadocsByIdResponses, GetSeadocsByIdErrors, ThrowOnError>({
        url: '/seadocs/{Id}',
        ...options
    });
};

export const getSeadocs = <ThrowOnError extends boolean = false>(options: Options<GetSeadocsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetSeadocsResponses, unknown, ThrowOnError>({
        url: '/seadocs',
        ...options
    });
};

/**
 * Получение данных специфичных для Seadox Api
 */
export const getUsersMe = <ThrowOnError extends boolean = false>(options?: Options<GetUsersMeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUsersMeResponses, unknown, ThrowOnError>({
        url: '/users/me',
        ...options
    });
};