// This file is auto-generated by @hey-api/openapi-ts

/**
 * PaginatedResponseOfSeadocInfo
 */
export type PaginatedResponseOfSeadocInfo = {
    total: number;
    data: Array<SeadocInfo>;
};

/**
 * SeadocInfo
 */
export type SeadocInfo = {
    id: string;
    name: string;
    description: string;
    ownerId: string;
    parentId: string | null;
    createdAt: string;
    updatedAt: string;
};

/**
 * SeadocModel
 */
export type SeadocModel = {
    /**
     * Lineage of this doc, from itself to its root ancestor
     */
    lineage: Array<SeadocInfo>;
    id: string;
    name: string;
    description: string;
    ownerId: string;
    parentId: string | null;
    createdAt: string;
    updatedAt: string;
};

export type SeadoxUserModel = {
    id: unknown;
    zitadelId: number;
    avatarUrl: string | null;
};

export type GetDevLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dev/login';
};

export type GetDevLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetSeadocsByIdData = {
    body?: never;
    path: {
        Id: string;
    };
    query?: never;
    url: '/seadocs/{Id}';
};

export type GetSeadocsByIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetSeadocsByIdResponses = {
    /**
     * OK
     */
    200: SeadocModel;
};

export type GetSeadocsByIdResponse = GetSeadocsByIdResponses[keyof GetSeadocsByIdResponses];

export type GetSeadocsData = {
    body?: never;
    path?: never;
    query: {
        Query?: string;
        /**
         * Offset (pagination)
         */
        Offset: number;
        /**
         * Count (pagination)
         */
        Limit: number;
    };
    url: '/seadocs';
};

export type GetSeadocsResponses = {
    /**
     * OK
     */
    200: PaginatedResponseOfSeadocInfo;
};

export type GetSeadocsResponse = GetSeadocsResponses[keyof GetSeadocsResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeResponses = {
    /**
     * OK
     */
    200: {
        user?: SeadoxUserModel;
    };
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/' | (string & {});
};