// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Seadox.CoreApi.Infrastructure.Data;

#nullable disable

namespace Seadox.CoreApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251228142217_AddedSeadocIsIndexed")]
    partial class AddedSeadocIsIndexed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Seadox.CoreApi.Features.Bookmarks.DocBookmark", b =>
                {
                    b.Property<int>("DocId")
                        .HasColumnType("integer")
                        .HasColumnName("doc_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("DocId", "UserId")
                        .HasName("pk_bookmarks");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bookmarks_user_id");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("Seadox.CoreApi.Features.Docs.Seadoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_indexed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seadocs");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_seadocs_owner_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_seadocs_parent_id");

                    b.ToTable("seadocs", (string)null);
                });

            modelBuilder.Entity("Seadox.CoreApi.Features.Uploads.Upload", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash")
                        .UseCollation("C");

                    b.Property<short>("Scope")
                        .HasColumnType("smallint")
                        .HasColumnName("scope");

                    b.Property<DateTimeOffset>("UploadTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_time");

                    b.Property<int>("UploaderId")
                        .HasColumnType("integer")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_uploads");

                    b.HasIndex("Hash")
                        .HasDatabaseName("ix_uploads_hash");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("ix_uploads_uploader_id");

                    b.ToTable("uploads", (string)null);
                });

            modelBuilder.Entity("Seadox.CoreApi.Features.Users.SeadoxUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<long>("StorageUsed")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_used");

                    b.Property<long>("ZitadelId")
                        .HasColumnType("bigint")
                        .HasColumnName("zitadel_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ZitadelId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_zitadel_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Seadox.CoreApi.Features.Bookmarks.DocBookmark", b =>
                {
                    b.HasOne("Seadox.CoreApi.Features.Docs.Seadoc", "Doc")
                        .WithMany()
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_seadocs_doc_id");

                    b.HasOne("Seadox.CoreApi.Features.Users.SeadoxUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_users_user_id");

                    b.Navigation("Doc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Seadox.CoreApi.Features.Docs.Seadoc", b =>
                {
                    b.HasOne("Seadox.CoreApi.Features.Users.SeadoxUser", "Owner")
                        .WithMany("Seadocs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seadocs_users_owner_id");

                    b.HasOne("Seadox.CoreApi.Features.Docs.Seadoc", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_seadocs_seadocs_parent_id");

                    b.OwnsOne("Seadox.CoreApi.Features.Access.DocumentShareMode", "Share", b1 =>
                        {
                            b1.Property<int>("SeadocId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<short>("Access")
                                .HasColumnType("smallint")
                                .HasColumnName("share_access");

                            b1.Property<short>("Type")
                                .HasColumnType("smallint")
                                .HasColumnName("share_type");

                            b1.HasKey("SeadocId");

                            b1.ToTable("seadocs");

                            b1.WithOwner()
                                .HasForeignKey("SeadocId")
                                .HasConstraintName("fk_seadocs_seadocs_id");
                        });

                    b.Navigation("Owner");

                    b.Navigation("Parent");

                    b.Navigation("Share")
                        .IsRequired();
                });

            modelBuilder.Entity("Seadox.CoreApi.Features.Uploads.Upload", b =>
                {
                    b.HasOne("Seadox.CoreApi.Features.Users.SeadoxUser", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uploads_users_uploader_id");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Seadox.CoreApi.Features.Docs.Seadoc", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Seadox.CoreApi.Features.Users.SeadoxUser", b =>
                {
                    b.Navigation("Seadocs");
                });
#pragma warning restore 612, 618
        }
    }
}
