// <auto-generated />
using System;
using CoreApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250715215229_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreApi.Features.Docs.Seadoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seadocs");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_seadocs_owner_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_seadocs_parent_id");

                    b.ToTable("seadocs", (string)null);
                });

            modelBuilder.Entity("CoreApi.Features.Users.SeadoxUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ZitadelId")
                        .HasColumnType("bigint")
                        .HasColumnName("zitadel_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ZitadelId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_zitadel_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CoreApi.Features.Docs.Seadoc", b =>
                {
                    b.HasOne("CoreApi.Features.Users.SeadoxUser", "Owner")
                        .WithMany("Seadocs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seadocs_users_owner_id");

                    b.HasOne("CoreApi.Features.Docs.Seadoc", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_seadocs_seadocs_parent_id");

                    b.Navigation("Owner");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CoreApi.Features.Docs.Seadoc", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("CoreApi.Features.Users.SeadoxUser", b =>
                {
                    b.Navigation("Seadocs");
                });
#pragma warning restore 612, 618
        }
    }
}
