/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSearchRouteImport } from './routes/docs/search'
import { Route as DocsIdRouteImport } from './routes/docs/$id'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiAuthSigninRouteImport } from './routes/api.auth.signin'
import { Route as ApiAuthCallbackRouteImport } from './routes/api.auth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSearchRoute = DocsSearchRouteImport.update({
  id: '/docs/search',
  path: '/docs/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIdRoute = DocsIdRouteImport.update({
  id: '/docs/$id',
  path: '/docs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSigninRoute = ApiAuthSigninRouteImport.update({
  id: '/api/auth/signin',
  path: '/api/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/$id': typeof DocsIdRoute
  '/docs/search': typeof DocsSearchRoute
  '/docs': typeof DocsIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/$id': typeof DocsIdRoute
  '/docs/search': typeof DocsSearchRoute
  '/docs': typeof DocsIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/$id': typeof DocsIdRoute
  '/docs/search': typeof DocsSearchRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/docs/$id'
    | '/docs/search'
    | '/docs'
    | '/api/auth/callback'
    | '/api/auth/signin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/docs/$id'
    | '/docs/search'
    | '/docs'
    | '/api/auth/callback'
    | '/api/auth/signin'
  id:
    | '__root__'
    | '/'
    | '/api/$'
    | '/docs/$id'
    | '/docs/search'
    | '/docs/'
    | '/api/auth/callback'
    | '/api/auth/signin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DocsIdRoute: typeof DocsIdRoute
  DocsSearchRoute: typeof DocsSearchRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSigninRoute: typeof ApiAuthSigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/search': {
      id: '/docs/search'
      path: '/docs/search'
      fullPath: '/docs/search'
      preLoaderRoute: typeof DocsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$id': {
      id: '/docs/$id'
      path: '/docs/$id'
      fullPath: '/docs/$id'
      preLoaderRoute: typeof DocsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signin': {
      id: '/api/auth/signin'
      path: '/api/auth/signin'
      fullPath: '/api/auth/signin'
      preLoaderRoute: typeof ApiAuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSplatRoute: ApiSplatRoute,
  DocsIdRoute: DocsIdRoute,
  DocsSearchRoute: DocsSearchRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSigninRoute: ApiAuthSigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
