// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteSeadocsByIdBookmarkData, DeleteSeadocsByIdBookmarkErrors, DeleteSeadocsByIdBookmarkResponses, DeleteSeadocsByIdData, DeleteSeadocsByIdErrors, DeleteSeadocsByIdResponses, DeleteUploadsByIdData, DeleteUploadsByIdErrors, DeleteUploadsByIdResponses, GetDevLoginData, GetDevLoginResponses, GetSeadocsByIdContentData, GetSeadocsByIdContentErrors, GetSeadocsByIdContentResponses, GetSeadocsByIdData, GetSeadocsByIdErrors, GetSeadocsByIdResponses, GetSeadocsData, GetSeadocsIndexData, GetSeadocsIndexResponses, GetSeadocsResponses, GetUploadsByIdData, GetUploadsByIdErrors, GetUploadsData, GetUploadsResponses, GetUsersMeData, GetUsersMeResponses, PatchSeadocsByIdData, PatchSeadocsByIdErrors, PatchSeadocsByIdResponses, PatchUsersMeData, PatchUsersMeResponses, PostSeadocsByIdBookmarkData, PostSeadocsByIdBookmarkErrors, PostSeadocsByIdBookmarkResponses, PostSeadocsData, PostSeadocsErrors, PostSeadocsResponses, PostUploadsData, PostUploadsErrors, PostUploadsMigrateData, PostUploadsMigrateErrors, PostUploadsMigrateResponses, PostUploadsResponses, PutSeadocsByIdContentData, PutSeadocsByIdContentErrors, PutSeadocsByIdContentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const deleteSeadocsByIdBookmark = <ThrowOnError extends boolean = false>(options: Options<DeleteSeadocsByIdBookmarkData, ThrowOnError>) => (options.client ?? client).delete<DeleteSeadocsByIdBookmarkResponses, DeleteSeadocsByIdBookmarkErrors, ThrowOnError>({ url: '/seadocs/{Id}/bookmark', ...options });

export const postSeadocsByIdBookmark = <ThrowOnError extends boolean = false>(options: Options<PostSeadocsByIdBookmarkData, ThrowOnError>) => (options.client ?? client).post<PostSeadocsByIdBookmarkResponses, PostSeadocsByIdBookmarkErrors, ThrowOnError>({ url: '/seadocs/{Id}/bookmark', ...options });

export const getDevLogin = <ThrowOnError extends boolean = false>(options?: Options<GetDevLoginData, ThrowOnError>) => (options?.client ?? client).get<GetDevLoginResponses, unknown, ThrowOnError>({ url: '/dev/login', ...options });

export const getSeadocs = <ThrowOnError extends boolean = false>(options: Options<GetSeadocsData, ThrowOnError>) => (options.client ?? client).get<GetSeadocsResponses, unknown, ThrowOnError>({ url: '/seadocs', ...options });

export const postSeadocs = <ThrowOnError extends boolean = false>(options: Options<PostSeadocsData, ThrowOnError>) => (options.client ?? client).post<PostSeadocsResponses, PostSeadocsErrors, ThrowOnError>({
    url: '/seadocs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteSeadocsById = <ThrowOnError extends boolean = false>(options: Options<DeleteSeadocsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteSeadocsByIdResponses, DeleteSeadocsByIdErrors, ThrowOnError>({ url: '/seadocs/{Id}', ...options });

export const getSeadocsById = <ThrowOnError extends boolean = false>(options: Options<GetSeadocsByIdData, ThrowOnError>) => (options.client ?? client).get<GetSeadocsByIdResponses, GetSeadocsByIdErrors, ThrowOnError>({ url: '/seadocs/{Id}', ...options });

export const patchSeadocsById = <ThrowOnError extends boolean = false>(options: Options<PatchSeadocsByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchSeadocsByIdResponses, PatchSeadocsByIdErrors, ThrowOnError>({
    url: '/seadocs/{Id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getSeadocsByIdContent = <ThrowOnError extends boolean = false>(options: Options<GetSeadocsByIdContentData, ThrowOnError>) => (options.client ?? client).get<GetSeadocsByIdContentResponses, GetSeadocsByIdContentErrors, ThrowOnError>({ url: '/seadocs/{Id}/content', ...options });

export const putSeadocsByIdContent = <ThrowOnError extends boolean = false>(options: Options<PutSeadocsByIdContentData, ThrowOnError>) => (options.client ?? client).put<PutSeadocsByIdContentResponses, PutSeadocsByIdContentErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/seadocs/{Id}/content',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const getSeadocsIndex = <ThrowOnError extends boolean = false>(options?: Options<GetSeadocsIndexData, ThrowOnError>) => (options?.client ?? client).get<GetSeadocsIndexResponses, unknown, ThrowOnError>({ url: '/seadocs/index', ...options });

export const deleteUploadsById = <ThrowOnError extends boolean = false>(options: Options<DeleteUploadsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteUploadsByIdResponses, DeleteUploadsByIdErrors, ThrowOnError>({ url: '/uploads/{Id}', ...options });

export const getUploadsById = <ThrowOnError extends boolean = false>(options: Options<GetUploadsByIdData, ThrowOnError>) => (options.client ?? client).get<unknown, GetUploadsByIdErrors, ThrowOnError>({ url: '/uploads/{Id}', ...options });

export const getUploads = <ThrowOnError extends boolean = false>(options: Options<GetUploadsData, ThrowOnError>) => (options.client ?? client).get<GetUploadsResponses, unknown, ThrowOnError>({ url: '/uploads', ...options });

export const postUploads = <ThrowOnError extends boolean = false>(options: Options<PostUploadsData, ThrowOnError>) => (options.client ?? client).post<PostUploadsResponses, PostUploadsErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/uploads',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const postUploadsMigrate = <ThrowOnError extends boolean = false>(options: Options<PostUploadsMigrateData, ThrowOnError>) => (options.client ?? client).post<PostUploadsMigrateResponses, PostUploadsMigrateErrors, ThrowOnError>({
    url: '/uploads/migrate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Получение данных специфичных для Seadox Api
 */
export const getUsersMe = <ThrowOnError extends boolean = false>(options?: Options<GetUsersMeData, ThrowOnError>) => (options?.client ?? client).get<GetUsersMeResponses, unknown, ThrowOnError>({ url: '/users/me', ...options });

/**
 * Изменение профиля в Seadox
 */
export const patchUsersMe = <ThrowOnError extends boolean = false>(options?: Options<PatchUsersMeData, ThrowOnError>) => (options?.client ?? client).patch<PatchUsersMeResponses, unknown, ThrowOnError>({
    url: '/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});
