// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from './client';
import type { DeleteSeadocsByIdBookmarkData, DeleteSeadocsByIdBookmarkResponses, DeleteSeadocsByIdBookmarkErrors, PostSeadocsByIdBookmarkData, PostSeadocsByIdBookmarkResponses, PostSeadocsByIdBookmarkErrors, GetColorsPaletteData, GetColorsPaletteResponses, GetDevLoginData, GetDevLoginResponses, GetSeadocsData, GetSeadocsResponses, PostSeadocsData, PostSeadocsResponses, PostSeadocsErrors, DeleteSeadocsByIdData, DeleteSeadocsByIdResponses, DeleteSeadocsByIdErrors, GetSeadocsByIdData, GetSeadocsByIdResponses, GetSeadocsByIdErrors, PatchSeadocsByIdData, PatchSeadocsByIdResponses, PatchSeadocsByIdErrors, GetSeadocsByIdContentData, GetSeadocsByIdContentResponses, GetSeadocsByIdContentErrors, PutSeadocsByIdContentData, PutSeadocsByIdContentResponses, PutSeadocsByIdContentErrors, GetSeadocsIndexData, GetSeadocsIndexResponses, DeleteUploadsByIdData, DeleteUploadsByIdResponses, DeleteUploadsByIdErrors, GetUploadsByIdData, GetUploadsByIdErrors, GetUploadsData, GetUploadsResponses, PostUploadsData, PostUploadsResponses, PostUploadsErrors, GetUsersMeData, GetUsersMeResponses, PatchUsersMeData, PatchUsersMeResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const deleteSeadocsByIdBookmark = <ThrowOnError extends boolean = false>(options: Options<DeleteSeadocsByIdBookmarkData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteSeadocsByIdBookmarkResponses, DeleteSeadocsByIdBookmarkErrors, ThrowOnError>({
        url: '/seadocs/{Id}/bookmark',
        ...options
    });
};

export const postSeadocsByIdBookmark = <ThrowOnError extends boolean = false>(options: Options<PostSeadocsByIdBookmarkData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostSeadocsByIdBookmarkResponses, PostSeadocsByIdBookmarkErrors, ThrowOnError>({
        url: '/seadocs/{Id}/bookmark',
        ...options
    });
};

/**
 * Получение цветов пользователей по умолчанию
 */
export const getColorsPalette = <ThrowOnError extends boolean = false>(options?: Options<GetColorsPaletteData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetColorsPaletteResponses, unknown, ThrowOnError>({
        url: '/colors/palette',
        ...options
    });
};

export const getDevLogin = <ThrowOnError extends boolean = false>(options?: Options<GetDevLoginData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDevLoginResponses, unknown, ThrowOnError>({
        url: '/dev/login',
        ...options
    });
};

export const getSeadocs = <ThrowOnError extends boolean = false>(options?: Options<GetSeadocsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSeadocsResponses, unknown, ThrowOnError>({
        url: '/seadocs',
        ...options
    });
};

export const postSeadocs = <ThrowOnError extends boolean = false>(options?: Options<PostSeadocsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostSeadocsResponses, PostSeadocsErrors, ThrowOnError>({
        url: '/seadocs',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const deleteSeadocsById = <ThrowOnError extends boolean = false>(options: Options<DeleteSeadocsByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteSeadocsByIdResponses, DeleteSeadocsByIdErrors, ThrowOnError>({
        url: '/seadocs/{Id}',
        ...options
    });
};

export const getSeadocsById = <ThrowOnError extends boolean = false>(options: Options<GetSeadocsByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetSeadocsByIdResponses, GetSeadocsByIdErrors, ThrowOnError>({
        url: '/seadocs/{Id}',
        ...options
    });
};

export const patchSeadocsById = <ThrowOnError extends boolean = false>(options: Options<PatchSeadocsByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<PatchSeadocsByIdResponses, PatchSeadocsByIdErrors, ThrowOnError>({
        url: '/seadocs/{Id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getSeadocsByIdContent = <ThrowOnError extends boolean = false>(options: Options<GetSeadocsByIdContentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetSeadocsByIdContentResponses, GetSeadocsByIdContentErrors, ThrowOnError>({
        url: '/seadocs/{Id}/content',
        ...options
    });
};

export const putSeadocsByIdContent = <ThrowOnError extends boolean = false>(options: Options<PutSeadocsByIdContentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutSeadocsByIdContentResponses, PutSeadocsByIdContentErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/seadocs/{Id}/content',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

export const getSeadocsIndex = <ThrowOnError extends boolean = false>(options?: Options<GetSeadocsIndexData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSeadocsIndexResponses, unknown, ThrowOnError>({
        url: '/seadocs/index',
        ...options
    });
};

export const deleteUploadsById = <ThrowOnError extends boolean = false>(options: Options<DeleteUploadsByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteUploadsByIdResponses, DeleteUploadsByIdErrors, ThrowOnError>({
        url: '/uploads/{Id}',
        ...options
    });
};

export const getUploadsById = <ThrowOnError extends boolean = false>(options: Options<GetUploadsByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, GetUploadsByIdErrors, ThrowOnError>({
        url: '/uploads/{Id}',
        ...options
    });
};

export const getUploads = <ThrowOnError extends boolean = false>(options?: Options<GetUploadsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUploadsResponses, unknown, ThrowOnError>({
        url: '/uploads',
        ...options
    });
};

export const postUploads = <ThrowOnError extends boolean = false>(options: Options<PostUploadsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostUploadsResponses, PostUploadsErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/uploads',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Получение данных специфичных для Seadox Api
 */
export const getUsersMe = <ThrowOnError extends boolean = false>(options?: Options<GetUsersMeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUsersMeResponses, unknown, ThrowOnError>({
        url: '/users/me',
        ...options
    });
};

/**
 * Изменение профиля в Seadox
 */
export const patchUsersMe = <ThrowOnError extends boolean = false>(options?: Options<PatchUsersMeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).patch<PatchUsersMeResponses, unknown, ThrowOnError>({
        url: '/users/me',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};