// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * AccessLevel
 */
export const zAccessLevel = z.enum([
    'None',
    'Read',
    'Write'
]);

/**
 * CreateDocRequest
 */
export const zCreateDocRequest = z.object({
    parentId: z.union([
        z.null(),
        z.string()
    ]),
    name: z.string()
});

/**
 * GetMeResponse
 */
export const zGetMeResponse = z.object({
    roles: z.array(z.string()),
    id: z.string(),
    zitadelId: z.coerce.bigint(),
    avatarUrl: z.union([
        z.null(),
        z.string()
    ]),
    color: z.string()
});

/**
 * IFormFile
 */
export const zIFormFile = z.string();

/**
 * SeadocInfo
 */
export const zSeadocInfo = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string(),
    isIndexed: z.boolean(),
    coverUrl: z.union([
        z.null(),
        z.string()
    ]),
    ownerId: z.string(),
    parentId: z.union([
        z.null(),
        z.string()
    ]),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime()
});

/**
 * GetIndexResponse
 */
export const zGetIndexResponse = z.object({
    root: z.array(zSeadocInfo),
    bookmarks: z.array(zSeadocInfo)
});

/**
 * PaginatedResponseOfSeadocInfo
 */
export const zPaginatedResponseOfSeadocInfo = z.object({
    total: z.int(),
    data: z.array(zSeadocInfo)
});

/**
 * SeadoxUserModel
 */
export const zSeadoxUserModel = z.object({
    id: z.string(),
    zitadelId: z.coerce.bigint(),
    avatarUrl: z.union([
        z.null(),
        z.string()
    ]),
    color: z.string()
});

/**
 * ShareType
 */
export const zShareType = z.enum(['CurrentOnly', 'Cascades']);

/**
 * DocumentShareMode
 */
export const zDocumentShareMode = z.object({
    access: zAccessLevel,
    type: zShareType
});

/**
 * SeadocModel
 */
export const zSeadocModel = z.object({
    accessLevel: zAccessLevel,
    share: zDocumentShareMode,
    lineage: z.array(zSeadocInfo),
    children: z.array(zSeadocInfo),
    id: z.string(),
    name: z.string(),
    description: z.string(),
    isIndexed: z.boolean(),
    coverUrl: z.union([
        z.null(),
        z.string()
    ]),
    ownerId: z.string(),
    parentId: z.union([
        z.null(),
        z.string()
    ]),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime()
});

/**
 * UpdateDocRequestBody
 */
export const zUpdateDocRequestBody = z.object({
    name: z.optional(z.string()),
    description: z.optional(z.string()),
    coverUrl: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    isIndexed: z.optional(z.boolean()),
    share: z.optional(zDocumentShareMode)
});

/**
 * UpdateMeRequest
 */
export const zUpdateMeRequest = z.object({
    color: z.optional(z.string()),
    avatarUrl: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

/**
 * UploadScope
 */
export const zUploadScope = z.enum([
    'Attachment',
    'Avatar',
    'Admin'
]);

/**
 * MigrateUploadRequest
 */
export const zMigrateUploadRequest = z.object({
    url: z.url(),
    scope: zUploadScope
});

/**
 * UploadModel
 */
export const zUploadModel = z.object({
    id: z.string(),
    uploaderId: z.string(),
    hash: z.string(),
    contentType: z.string(),
    fileName: z.string(),
    fileSize: z.coerce.bigint(),
    uploadTime: z.iso.datetime(),
    scope: zUploadScope
});

/**
 * PaginatedResponseOfUploadModel
 */
export const zPaginatedResponseOfUploadModel = z.object({
    total: z.int(),
    data: z.array(zUploadModel)
});

export const zDeleteSeadocsByIdBookmarkData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        Id: z.string()
    }),
    query: z.optional(z.never())
});

export const zPostSeadocsByIdBookmarkData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        Id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetDevLoginData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetSeadocsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        Offset: z.int().default(0),
        Limit: z.int().default(10),
        Prompt: z.optional(z.string())
    })
});

/**
 * OK
 */
export const zGetSeadocsResponse = zPaginatedResponseOfSeadocInfo;

export const zPostSeadocsData = z.object({
    body: zCreateDocRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostSeadocsResponse = zSeadocModel;

export const zDeleteSeadocsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        Id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetSeadocsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        Id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSeadocsByIdResponse = zSeadocModel;

export const zPatchSeadocsByIdData = z.object({
    body: zUpdateDocRequestBody,
    path: z.object({
        Id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPatchSeadocsByIdResponse = zSeadocModel;

export const zGetSeadocsByIdContentData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        Id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * No Content
 */
export const zGetSeadocsByIdContentResponse = z.void();

export const zPutSeadocsByIdContentData = z.object({
    body: z.object({
        Content: zIFormFile
    }),
    path: z.object({
        Id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetSeadocsIndexData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSeadocsIndexResponse = zGetIndexResponse;

export const zDeleteUploadsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        Id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetUploadsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        Id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetUploadsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        Offset: z.int().default(0),
        Limit: z.int().default(10),
        Scope: z.optional(z.enum([
            'Attachment',
            'Avatar',
            'Admin'
        ])),
        Prompt: z.optional(z.string())
    })
});

/**
 * OK
 */
export const zGetUploadsResponse = zPaginatedResponseOfUploadModel;

export const zPostUploadsData = z.object({
    body: z.object({
        File: zIFormFile,
        Scope: zUploadScope
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostUploadsResponse = zUploadModel;

export const zPostUploadsMigrateData = z.object({
    body: zMigrateUploadRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostUploadsMigrateResponse = zUploadModel;

export const zGetUsersMeData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetUsersMeResponse = zGetMeResponse;

export const zPatchUsersMeData = z.object({
    body: z.optional(zUpdateMeRequest),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPatchUsersMeResponse = zSeadoxUserModel;
