name: Deploy
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push core api
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./coreapi/Dockerfile
          tags: ${{ secrets.REGISTRY }}/seadox-v2/core-api:latest

      - name: Build and push web
        uses: docker/build-push-action@v6
        with:
          push: true
          target: web
          build-args: |
            VITE_WS_URL=wss://ws.seadox.ru
            VITE_ZITADEL_URL=https://iam.seadox.ru
          tags: ${{ secrets.REGISTRY }}/seadox-v2/web:latest

      - name: Build and push ws
        uses: docker/build-push-action@v6
        with:
          push: true
          target: ws
          tags: ${{ secrets.REGISTRY }}/seadox-v2/ws:latest

      - name: Calling portainer webhooks
        run: |
          sleep 10s
          curl -fail -X POST ${{ secrets.CORE_API_WEBHOOK_URL }}
          curl -fail -X POST ${{ secrets.WEB_WEBHOOK_URL }} |
          curl -fail -X POST ${{ secrets.WS_WEBHOOK_URL }}