name: Deploy
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          target: web
          tags: un1ver5e/seadox-web:latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          target: ws
          tags: un1ver5e/seadox-ws:latest

      - name: Calling portainer webhooks
        run: |
          curl -fail  -X POST ${{ secrets.WEB_WEBHOOK_URL }} |
          curl -fail  -X POST ${{ secrets.WS_WEBHOOK_URL }}